# Generated by Django 4.2.5 on 2023-09-14 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('stock', models.IntegerField()),
                ('img', models.ImageField(upload_to='product')),
                ('available', models.BooleanField()),
                ('price', models.IntegerField()),
                ('desc', models.TextField()),
                ('date', models.DateTimeField()),
                ('cate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.categ')),
            ],
        ),
    ]
